name: Deploy to IoT

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.x
#
#      - name: Install Dependencies
#        run: pip install -r requirements.txt

      - name: Create Deployment Package
        run: zip -r project.zip .

      - name: Configure AWS Access OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          commit-id: ${{ github.event.head_commit.id }}
          role-to-assume:  ${{ secrets.STAGING_DEPLOY_ROLE_ARN }}
          role-session-name: github-deploy-staging-${{ github.event.head_commit.id }}
          aws-region: ${{ vars.REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp project.zip s3://iot-deployments-us-west-2-prod/
