name: Deploy to IoT

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.x
#
#      - name: Install Dependencies
#        run: pip install -r requirements.txt

      - name: Create Deployment Package
        run: zip -r project.zip .

      - name: Configure AWS Access OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          github-role-arn: ${{ secrets.STAGING_DEPLOY_ROLE_ARN }}
          commit-id: ${{ github.event.head_commit.id }}
          role-to-assume: ${{ inputs.github-role-arn }}
          role-session-name: github-deploy-${{ inputs.environment }}-${{ github.event.head_commit.id }}
          aws-region: ${{ vars.REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp project.zip s3://iot-deployments-prod/
